'use strict';

(function () {
  var MAP_PIN_MAIN_WIDTH = 64;
  var MAP_PIN_MAIN_HEIGHT = 65;
  var MAP_PIN_MAIN_HEIGHT_ACTIVE = 87;

  window.constants = {
    MAP_PIN_MAIN_WIDTH: MAP_PIN_MAIN_WIDTH,
    MAP_PIN_MAIN_HEIGHT: MAP_PIN_MAIN_HEIGHT,
    MAP_PIN_MAIN_HEIGHT_ACTIVE: MAP_PIN_MAIN_HEIGHT_ACTIVE
  };

})();
